[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
